[default]
Experimental_building_Chiodo_2=params_other.asp
Office_Buildings_Cubo_18_B=params_cubo_18B.asp
Office_Buildings_Cubo_31B=params_other.asp
Office_Buildings_Cubo_41B=params_cubo_18B.asp
Office_Buildings_Cubo_44B=params_other.asp
Residential_buildings_Monaci121=params_other.asp
Residential_buildings_Monaci122=params_other.asp
Residential_buildings_Monaci123=params_other.asp
Residential_buildings_Monaci124=params_other.asp
Residential_buildings_Monaci223=params_other.asp
